---
name: Deployment
on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy infrastructure
        working-directory: terraform
        env:
          TF_VAR_GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          TF_VAR_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > ./credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(realpath ./credentials.json)
          terraform init --backend-config "bucket=${{ secrets.GCP_BACKEND_BUCKET }}"
          terraform apply --input=false --auto-approve
