---
name: Deployment
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
      - name: Deploy infrastructure
        working-directory: terraform
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > ./credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(realpath ./credentials.json)
          terraform init --backend-config "bucket=${{ secrets.GCP_BACKEND_BUCKET }}"
          terraform apply --auto-approve
