---
name: Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          GCP_CREDENTIALS: ${{ secrets.TF_VAR_GCP_CREDENTIALS }}
          GCP_PROJECT: ${{ secrets.TF_VAR_GCP_PROJECT }}
          GCP_REGION: ${{ secrets.TF_VAR_GCP_REGION }}
      - run: terraform fmt --check
      - run: terraform init --backend-config "bucket=${{ secrets.TF_VAR_BACKEND_BUCKET }}"
      - run: terraform validate
      - run: terraform plan
